name: Terraform CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment to deploy"
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prod

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest

    env:
      TF_VAR_environment: ${{ github.event.inputs.environment || 'dev' }}

    defaults:
      run:
        shell: bash
        working-directory: terraform/environments/${{ github.event.inputs.environment || 'dev' }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Format Check
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'
      run: terraform apply -auto-approve tfplan

    - name: Slack Notification (optional)
      if: always()
      run: |
        curl -X POST -H 'Content-type: application/json'         --data '{
          "text":"✅ *${{ github.event.inputs.environment || 'dev' }}* infra deployed by *${{ github.actor }}* in repo *${{ github.repository }}*"
        }' ${{ secrets.SLACK_WEBHOOK_URL }}
